[theme]
primaryColor = "#167D9A"
backgroundColor = "#F6F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#192B43"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
